{{- $root := . -}}
{{- if .Values.features.ingress.enabled -}}
{{- with $service := .Values.services.redis }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $root.Release.Name }}-public
  labels:
    app.kubernetes.io/component: "service"
    app.kubernetes.io/instance: {{ $root.Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ $root.Release.Service | quote }}
    app.kubernetes.io/name: {{ default $root.Chart.Name $root.Values.nameOverride | trunc 63 | trimSuffix "-" | quote }}
    app.kubernetes.io/version: {{ default $root.Chart.Version $root.Chart.AppVersion | quote }}
    helm.sh/chart: {{ printf "%s-%s" $root.Chart.Name ($root.Chart.Version | replace "+" "_") | quote }}
spec:
  type: ClusterIP
  selector:
    quarks.cloudfoundry.org/instance-group-name: redis
    quarks.cloudfoundry.org/deployment-name: {{ $root.Values.deployment_name }}
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: {{ $service.type | quote }}
  {{- if gt (len $service.externalIPs) 0 }}
  externalIPs: {{ $service.externalIPs | toJson }}
  {{- end }}
  {{- if $service.clusterIP }}
  clusterIP: {{ $service.clusterIP | quote }}
  {{- end }}
  {{- if $service.loadBalancerIP }}
  loadBalancerIP: {{ $service.loadBalancerIP | quote }}
  {{- end }}
{{- end }}
{{- end }}
