---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name | quote }}
  labels:
    app.kubernetes.io/component: "service"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" | quote }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_") | quote }}
spec:
  type: ClusterIP
  selector:
    fissile.cloudfoundry.org/instance-group-name: redis
    fissile.cloudfoundry.org/deployment-name: {{ .Values.deployment_name }}
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
